apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: arik-component
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/achernet-tenant/go-basic-app-test-arik/arik-component@sha256:8b46442e29910167357a0afcf9b90259f0b93b4cdca5ef1fa9ee65dc973efbe0
        name: my-go
        resources: {}
status: {}
