apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: arik-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: arik-component
    app.kubernetes.io/part-of: go-basic-app-test-arik
  name: arik-componentvtzz
spec:
  path: /
  port:
    targetPort: 8081
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: arik-component
    weight: null
status: {}
